### ISSUE TITLE
Cannot display subnet address prefix info

### ISSUE THREAD

**Issue by yidouer** [HarvestingClouds/PowerShellSamples#7]
Hello Aman,
Thank you for developing this script and it is really useful for a network engineer like me. Everything works well in this script "Report-UDRsWithSubnetInfo.ps1" except the subnetAddressPrefix column won't show any info, not sure if you have time to take a look. thanks again.

Roy

**Comment by HarvestingClouds** [comment]
hi @yidouer,

I have updated the script to provide subnet address prefix. I have also updated the script to target the new Az module. 
If you haven't yet updated to Az module in PowerShell you can do so by following the guidelines here: https://docs.microsoft.com/en-us/powershell/azure/new-azureps-module-az?view=azps-4.6.1

I hope this helps. I will keep the issue open for a couple days.

**Comment by yidouer** [comment]
Thank you so much Aman for the help. I will test and let you know how it
goes. thanks.

Roy

**Comment by HarvestingClouds** [comment]
Closing the issue as this is fixed in the updated script.
